# Generated by Django 5.1.7 on 2025-04-26 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=200)),
                ('dat', models.DateField(default=datetime.date.today)),
                ('select', models.TextField(max_length=250)),
            ],
        ),
    ]
